name: xmonad-robin
version: 0.0.1
synopsis: xmonad config of Robin
maintainer: Robin Van den Broeck <robin.broeck@gmail.com>
github: robinvdbroeck/dotfiles

dependencies:
  - base
  - xmonad >= 0.17.0 && < 0.18.0
  - xmonad-contrib >= 0.17.0 && < 0.18.0
  - dbus
  - utf8-string

executables:
  xmonad-robin:
    main: config.hs
